
name: 🚀 Deploy Allure report 

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Get Allure history
      uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
          ref: gh-pages
          path: gh-pages

    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results
        allure_history: allure-history      

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.2.2
      with:
          branch: gh-pages
          folder: allure-history
